# Generated by Django 5.1.5 on 2025-02-07 13:19

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.upload_to),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
