# Generated by Django 5.1.5 on 2025-03-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_professor_imagem_alter_professor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('disciplinas', models.CharField(max_length=30)),
                ('aulas', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='professor',
            name='ni',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
